//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S2B.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCIONARIO
    {
        public int COD_FUNCIONARIO { get; set; }
        public string NOME { get; set; }
        public string CPF { get; set; }
        public string LOGIN { get; set; }
        public string SENHA { get; set; }
        public string EMAIL { get; set; }
        public string ENDERECO { get; set; }
        public string TELEFONE { get; set; }
        public string CELULAR { get; set; }
        public string TIPO { get; set; }
    }
}
